version: '3.8'
services:
  nginx:
    image: nginx:latest
      container_name: nginx
      build:
        context: ./
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites-available:/etc/nginx/sites-available
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/letsencrypt:/etc/letsencrypt
        - ./public:/var/www/public
      networks:
        - net_local
        - geral
        - net_swarm
      deploy:
        replicas: 1
      restart_policy:
        condition: on-failure

networks:
  net_local:
    driver: bridge
  geral:
    external: true
  net_swarm:
    external: true
    attachable: true
    name: net_swarm
